import { useState } from 'react'
import { ArrowLeft, ArrowRight, Box, Check, ChevronRight, GitCompareArrows, History, Lightbulb, LockKeyhole, Megaphone, Plus, ShieldCheck, Sprout, Users, Wallet, Workflow } from 'lucide-react'
import { areas, project, TODAY } from '../data/seed'
import { actorFor, approvedDiagnostics, compareDiagnostics, uid } from '../data/repository'
import type { Diagnostic } from '../data/types'
import { Badge, Button, Delta, Empty, Field, Heading, Modal, Notice, Panel, Steps, TextLink } from '../ui'
import { dateLabel, useData } from '../state'

const areaIcons = { Lightbulb, Box, Users, Megaphone, Wallet, Workflow, ShieldCheck, Sprout }
export function AreaIcon({ areaId }: { areaId: string }) { const area = areas.find(a => a.id === areaId)!; const Icon = areaIcons[area.icon as keyof typeof areaIcons]; return <span className={`area-icon ${area.color}`}><Icon size={21} strokeWidth={1.6} /></span> }
export function Radar({ previous, current }: { previous: Diagnostic; current: Diagnostic }) {
  const point = (i: number, score: number) => { const angle = i * Math.PI / 4 - Math.PI / 2; return `${180 + Math.cos(angle) * score * 23},${165 + Math.sin(angle) * score * 23}` }
  return <svg className="radar" viewBox="0 0 360 335" role="img" aria-label={`Comparación de ocho áreas entre ${previous.date} y ${current.date}. Los valores se detallan en las tarjetas y la tabla de evolución.`}>{[1, 2, 3, 4, 5].map(n => <polygon key={n} points={areas.map((_, i) => point(i, n)).join(' ')} fill={n % 2 ? '#f8f8f3' : '#fff'} stroke="#e5e5db" />).reverse()}{areas.map((a, i) => <line key={a.id} x1="180" y1="165" x2={point(i, 5).split(',')[0]} y2={point(i, 5).split(',')[1]} stroke="#e5e5db" />)}<polygon points={areas.map((a, i) => point(i, previous.assessments.find(x => x.areaId === a.id)?.score ?? 0)).join(' ')} fill="#8fa0d820" stroke="#8fa0d8" strokeWidth="1.8" strokeDasharray="4 4" /><polygon points={areas.map((a, i) => point(i, current.assessments.find(x => x.areaId === a.id)?.score ?? 0)).join(' ')} fill="#8a85412b" stroke="#8a8541" strokeWidth="2.2" />{areas.map((a, i) => { const p = point(i, current.assessments.find(x => x.areaId === a.id)?.score ?? 0).split(','); const pos = point(i, 6.1).split(','); return <g key={a.id}><circle cx={p[0]} cy={p[1]} r="3.4" fill="#8a8541" stroke="white" strokeWidth="1.5" /><text x={pos[0]} y={pos[1]} textAnchor="middle" dominantBaseline="middle" fontSize="10" fill="#66675d">{['Negocio', 'Producto', 'Mercado', 'Ventas', 'Finanzas', 'Equipo', 'Legal', 'Impacto'][i]}</text></g> })}</svg>
}
export function Diagnostics({ focusId }: { focusId?: string }) {
  const { data, role, run, navigate, busy } = useData()
  const approved = approvedDiagnostics(data)
  const [selected, setSelected] = useState(focusId ?? approved.at(-1)?.id ?? data.diagnostics[0]?.id)
  const [editor, setEditor] = useState<Diagnostic | 'new' | null>(null)
  const [areaId, setAreaId] = useState<string | null>(null)
  const [history, setHistory] = useState(false)
  const [confirm, setConfirm] = useState(false)
  const current = data.diagnostics.find(d => d.id === selected) ?? approved.at(-1)
  const previous = current ? approved.filter(d => d.date < current.date).at(-1) : undefined
  const comparison = previous && current?.status === 'APPROVED' ? compareDiagnostics(previous, current) : []
  const score = current ? current.assessments.reduce((sum, a) => sum + a.score, 0) / current.assessments.length : 0
  const assessed = current?.assessments.find(a => a.areaId === areaId)
  return <>
    <Heading eyebrow="Comprender para avanzar" title="Diagnóstico 360°" description="Una mirada integral a tu emprendimiento, en cada etapa de su camino." action={<><Button variant="secondary" onClick={() => setHistory(true)}><History size={16} /> Historial</Button><Button onClick={() => setEditor('new')}><Plus size={17} /> Nuevo diagnóstico</Button></>} />
    {!current ? <Empty text="Crea la primera fotografía del emprendimiento para comenzar su seguimiento." action={<Button onClick={() => setEditor('new')}>Crear diagnóstico</Button>} /> : <>
      <div className="diagnostic-toolbar"><div className="inline"><span className="eyebrow">Fotografía del proyecto</span><select aria-label="Seleccionar diagnóstico" value={current.id} onChange={e => setSelected(e.target.value)}>{data.diagnostics.toSorted((a, b) => b.date.localeCompare(a.date)).map(d => <option key={d.id} value={d.id}>{dateLabel(d.date)} · {d.type === 'INITIAL' ? 'Inicial' : d.type === 'CLOSURE' ? 'Cierre' : 'Seguimiento'}{d.supersedes ? ' · revisión' : ''}</option>)}</select><Badge status={current.status} /></div><span className="muted small">Realizado por {current.author}</span></div>
      {current.status === 'DRAFT' && <Notice>Borrador guardado. <TextLink onClick={() => setEditor(current)}>Continuar diagnóstico</TextLink><Button variant="secondary" disabled={busy || role === 'Emprendedor' && current.author !== actorFor(role)} onClick={() => run({ type: 'diagnostic.status', id: current.id, status: 'SUBMITTED' }, 'Diagnóstico enviado a revisión')}>Enviar a revisión</Button></Notice>}
      {current.status === 'SUBMITTED' && role !== 'Emprendedor' && <Notice>Revisa las evaluaciones antes de aprobar esta fotografía. <Button variant="secondary" onClick={() => run({ type: 'diagnostic.status', id: current.id, status: 'DRAFT' }, 'Devuelto a borrador')}>Devolver a borrador</Button><Button onClick={() => setConfirm(true)}>Aprobar diagnóstico</Button></Notice>}
      <div className="diagnostic-overview"><Panel className="radar-panel"><div className="panel-heading"><h2>La perspectiva completa</h2><span className="small muted">Escala de 1 a 5</span></div><Radar current={current} previous={previous ?? current} /><div className="chart-legend"><span><i className="legend-dot olive" />{dateLabel(current.date)}</span>{previous && <span><i className="legend-dot blue" />{dateLabel(previous.date)}</span>}</div></Panel><div className="diagnostic-story"><p className="eyebrow">Una fotografía, nuevas posibilidades</p><div className="score"><strong>{score.toFixed(1)}</strong><span>/ 5<br /><small>promedio de las áreas</small></span></div><h2>{current.status === 'APPROVED' ? 'Cada avance cuenta.' : 'Tu próxima fotografía está en camino.'}</h2><p>{current.observation}</p><div className="evolution-counts"><div><strong>{comparison.filter(a => (a.delta ?? 0) > 0).length}</strong><span>áreas avanzan <ArrowRight size={13} /></span></div><div><strong>{comparison.filter(a => a.delta === 0).length}</strong><span>sin cambio</span></div><div><strong>{comparison.filter(a => (a.delta ?? 0) < 0).length}</strong><span>en retroceso</span></div></div>{previous && current.status === 'APPROVED' ? <TextLink onClick={() => navigate('Evolución', current.id)}>Explorar la evolución</TextLink> : <p className="small muted">La comparación estará disponible con dos diagnósticos aprobados.</p>}</div></div>
      <div className="section-heading"><div><h2>Ocho áreas, un mismo propósito</h2><p className="muted">Explora cada área para entender sus hallazgos y necesidades.</p></div><span className="small muted">{current.assessments.length} áreas evaluadas</span></div>
      <div className="area-grid">{current.assessments.map(a => { const delta = comparison.find(c => c.areaId === a.areaId)?.delta; const needs = data.needs.filter(n => n.areaId === a.areaId && !['ADDRESSED', 'DISCARDED'].includes(n.status)); return <button className="area-card" key={a.areaId} onClick={() => setAreaId(a.areaId)}><div className="area-card-top"><AreaIcon areaId={a.areaId} /><span className="area-score">{a.score}<small>/5</small></span></div><h3>{a.name}</h3><p>{a.question}</p><div className="score-segments" aria-label={`${a.score} de 5`}>{[1, 2, 3, 4, 5].map(n => <span key={n} className={n <= a.score ? `filled ${areas.find(x => x.id === a.areaId)?.color}` : ''} />)}</div><div className="area-card-bottom"><Delta value={delta} /><span>{needs.length ? `${needs.length} ${needs.length === 1 ? 'necesidad' : 'necesidades'}` : 'Sin necesidades abiertas'}<ChevronRight size={14} /></span></div></button> })}</div>
      <div className="footnote"><LockKeyhole size={14} />{current.status === 'APPROVED' ? `Fotografía aprobada por ${current.approvedBy} el ${dateLabel(current.approvedAt ?? current.date)}. Se conserva sin cambios.` : 'Los borradores aún no forman parte de la comparación histórica.'}</div>
    </>}
    {editor && <DiagnosticEditor initial={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} onSaved={id => { setSelected(id); setEditor(null) }} />}
    {history && <Modal title="Historial de diagnósticos" description="Cada fotografía conserva su fecha, autor y aprobación." onClose={() => setHistory(false)}>{data.diagnostics.toSorted((a, b) => b.date.localeCompare(a.date)).map(d => <button className="record-row" key={d.id} onClick={() => { setSelected(d.id); setHistory(false) }}><span className="timeline-dot"><History size={18} /></span><div><strong>{dateLabel(d.date)} · {d.type === 'INITIAL' ? 'Inicial' : 'Seguimiento'}</strong><p>{d.author}{d.supersedes ? ' · Nueva revisión vinculada' : ''}</p><small>{d.approvedBy && `Aprobado por ${d.approvedBy}`}</small></div><Badge status={d.status} /><ChevronRight size={16} /></button>)}{current?.status === 'APPROVED' && <Button variant="secondary" disabled={busy} onClick={async () => { const next = await run({ type: 'diagnostic.revise', id: current.id }, 'Nueva revisión creada; el original se conserva'); if (next) { setSelected(next.diagnostics.at(-1)!.id); setEditor(next.diagnostics.at(-1)!); setHistory(false) } }}>Crear revisión de la fotografía seleccionada</Button>}</Modal>}
    {assessed && current && <Modal title={assessed.name} description={assessed.question} onClose={() => setAreaId(null)}><div className="inline"><AreaIcon areaId={assessed.areaId} /><strong className="large">{assessed.score} / 5</strong><Delta value={comparison.find(a => a.areaId === assessed.areaId)?.delta} /></div><h3>Observaciones</h3><p>{assessed.observation}</p><h3>Notas de la evaluación</h3><p className="muted">{assessed.notes || 'Sin notas adicionales.'}</p><h3>Evidencia contextual</h3>{assessed.evidenceIds.length ? assessed.evidenceIds.map(id => <TextLink key={id} onClick={() => navigate('Evidencias', id)}>{data.evidence.find(e => e.id === id)?.title}</TextLink>) : <p className="muted">Sin evidencia contextual registrada.</p>}<h3>Necesidades relacionadas</h3>{data.needs.filter(n => n.areaId === assessed.areaId).map(n => <button className="record-row" key={n.id} onClick={() => navigate('Necesidades', n.id)}><div><strong>{n.title}</strong><p>Detectada el {dateLabel(n.date)}</p></div><Badge status={n.status} /><ChevronRight size={16} /></button>)}<div className="modal-actions"><Button onClick={() => navigate('Necesidades', `new:${current.id}:${assessed.areaId}`)}><Plus size={16} /> Detectar necesidad</Button></div></Modal>}
    {confirm && current && <Modal title="Aprobar diagnóstico" onClose={() => setConfirm(false)}><Notice>Esta fotografía quedará inmutable y formará parte de la comparación. Una corrección requiere una nueva revisión.</Notice><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirm(false)}>Cancelar</Button><Button disabled={busy} onClick={async () => { if (await run({ type: 'diagnostic.status', id: current.id, status: 'APPROVED' }, 'Diagnóstico aprobado y agregado a la evolución')) setConfirm(false) }}>Confirmar aprobación</Button></div></Modal>}
  </>
}
function DiagnosticEditor({ initial, onClose, onSaved }: { initial?: Diagnostic; onClose: () => void; onSaved: (id: string) => void }) {
  const { role, data, run, busy } = useData()
  const [draft, setDraft] = useState<Diagnostic>(() => initial ? structuredClone(initial) : { id: uid(), projectId: project.id, date: TODAY, type: 'FOLLOW_UP', author: actorFor(role), status: 'DRAFT', observation: '', assessments: areas.map(a => ({ areaId: a.id, name: a.name, question: a.question, score: 1, observation: '', notes: '', evidenceIds: [] })) })
  const [step, setStep] = useState(0)
  const [error, setError] = useState('')
  const assessment = draft.assessments[Math.max(0, step - 1)]
  const changeArea = (patch: Partial<typeof assessment>) => setDraft(d => ({ ...d, assessments: d.assessments.map((a, i) => i === step - 1 ? { ...a, ...patch } : a) }))
  return <Modal title={initial ? 'Continuar diagnóstico' : 'Una nueva mirada al proyecto'} description="Completa cada área a tu ritmo. Puedes guardar un borrador en cualquier momento." onClose={onClose} wide><Steps labels={['Contexto', 'Evaluación por áreas', 'Revisión']} current={step === 0 ? 0 : step <= areas.length ? 1 : 2} />{error && <Notice tone="error">{error}</Notice>}
    {step === 0 ? <div className="form-grid"><Field label="Fecha del diagnóstico"><input required type="date" value={draft.date} max={TODAY} onChange={e => setDraft({ ...draft, date: e.target.value })} /></Field><Field label="Tipo de diagnóstico"><select value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value as Diagnostic['type'] })}><option value="INITIAL">Inicial</option><option value="FOLLOW_UP">Seguimiento</option><option value="CLOSURE">Cierre</option></select></Field><div className="span-2"><Field label="Observación general"><textarea value={draft.observation} onChange={e => setDraft({ ...draft, observation: e.target.value })} placeholder="¿En qué momento se encuentra el emprendimiento?" rows={4} /></Field></div></div> : step <= areas.length ? <div><div className="area-step-header"><AreaIcon areaId={assessment.areaId} /><div><p className="eyebrow">Área {step} de {areas.length}</p><h3>{assessment.name}</h3></div></div><p>{assessment.question}</p><Field label="Calificación del área"><div className="rating">{[1, 2, 3, 4, 5].map(n => <button type="button" key={n} aria-pressed={assessment.score === n} className={assessment.score === n ? 'selected' : ''} onClick={() => changeArea({ score: n })}>{n}</button>)}</div></Field><div className="rating-labels"><span>1 · Menor desarrollo</span><span>5 · Mayor desarrollo</span></div><Field label="Observaciones"><textarea rows={3} placeholder="Describe la situación y los hallazgos del área" value={assessment.observation} onChange={e => changeArea({ observation: e.target.value })} /></Field><Field label="Notas por aspecto"><textarea rows={2} value={assessment.notes} onChange={e => changeArea({ notes: e.target.value })} placeholder="Aspecto evaluado y respuesta del equipo" /></Field><Field label="Evidencia contextual (opcional)"><select value={assessment.evidenceIds[0] ?? ''} onChange={e => changeArea({ evidenceIds: e.target.value ? [e.target.value] : [] })}><option value="">Sin evidencia seleccionada</option>{data.evidence.map(e => <option key={e.id} value={e.id}>{e.title}</option>)}</select></Field></div> : <><Notice tone="success">Las ocho áreas están listas para revisar. El diagnóstico se guardará como borrador antes de enviarlo a validación.</Notice>{draft.assessments.map(a => <div className="record-row" key={a.areaId}><AreaIcon areaId={a.areaId} /><div><strong>{a.name}</strong><p>{a.observation || 'Sin observaciones adicionales'}</p></div><b>{a.score}/5</b></div>)}</>}
    <div className="modal-actions"><Button variant="ghost" disabled={busy} onClick={async () => { if (!draft.date || draft.date > TODAY) { setError('Selecciona una fecha válida hasta el 7 de septiembre de 2026.'); return } if (await run({ type: 'diagnostic.save', value: draft }, 'Borrador guardado')) onSaved(draft.id) }}>Guardar borrador</Button><div className="inline">{step > 0 && <Button variant="secondary" onClick={() => setStep(step - 1)}><ArrowLeft size={15} /> Atrás</Button>}{step <= areas.length ? <Button onClick={() => { if (!draft.date || draft.date > TODAY) { setError('Selecciona una fecha válida.'); return }; setError(''); setStep(step + 1) }}>Continuar <ArrowRight size={15} /></Button> : <Button disabled={busy} onClick={async () => { if (await run({ type: 'diagnostic.save', value: draft }, 'Diagnóstico guardado para revisión')) onSaved(draft.id) }}><Check size={16} /> Guardar diagnóstico</Button>}</div></div>
  </Modal>
}
export function Evolution({ focusId }: { focusId?: string }) {
  const { data, navigate } = useData()
  const approved = approvedDiagnostics(data)
  const [selected, setSelected] = useState(focusId ?? approved.at(-1)?.id)
  const current = approved.find(d => d.id === selected) ?? approved.at(-1)
  const previous = approved[approved.findIndex(d => d.id === current?.id) - 1]
  return <><Heading eyebrow="El camino recorrido" title="Evolución del emprendimiento" description="Compara fotografías aprobadas consecutivas y sigue los cambios por área." action={<Button variant="secondary" onClick={() => navigate('Diagnóstico 360°')}><ArrowLeft size={16} /> Ver diagnóstico</Button>} /><div className="comparison-picker"><GitCompareArrows size={20} /><span>{previous ? dateLabel(previous.date) : 'Sin diagnóstico anterior'}</span><ArrowRight size={18} /><select aria-label="Diagnóstico actual para comparar" value={current?.id ?? ''} onChange={e => setSelected(e.target.value)}>{approved.map(d => <option key={d.id} value={d.id}>{dateLabel(d.date)}</option>)}</select><Badge status="APPROVED" /></div>{current && previous ? <><div className="evolution-layout"><Panel title="Una perspectiva en el tiempo"><Radar current={current} previous={previous} /><div className="chart-legend"><span><i className="legend-dot blue" />Anterior</span><span><i className="legend-dot olive" />Actual</span></div></Panel><Panel title="Cambio por área"><div className="table-scroll"><table><thead><tr><th>Área</th><th>Anterior</th><th>Actual</th><th>Cambio</th></tr></thead><tbody>{compareDiagnostics(previous, current).map(a => <tr key={a.areaId}><td>{a.name}</td><td>{a.before ?? '—'}/5</td><td><b>{a.score}/5</b></td><td><Delta value={a.delta} /></td></tr>)}</tbody></table></div></Panel></div><Notice>Los cambios describen la evolución observada. No atribuyen causas automáticamente ni cambian el estado de las necesidades.</Notice><Panel title="Del hallazgo al trabajo realizado">{data.needs.map(n => <button className="record-row" key={n.id} onClick={() => navigate('Necesidades', n.id)}><AreaIcon areaId={n.areaId} /><div><strong>{n.title}</strong><p>{n.objectiveIds.length} objetivos vinculados · Detectada el {dateLabel(n.date)}</p></div><Badge status={n.status} /><ChevronRight size={16} /></button>)}</Panel></> : <Empty title="Cada camino empieza con una fotografía" text="Necesitas dos diagnósticos aprobados para comparar la evolución por área." action={<Button onClick={() => navigate('Diagnóstico 360°')}>Ir a diagnósticos</Button>} />}</>
}
