import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronRight, FileCheck2, FileText, History, Link2, LockKeyhole, Plus, Printer } from 'lucide-react'
import { makeReport, reportSources } from '../data/repository'
import { project, TODAY } from '../data/seed'
import type { Report, Source } from '../data/types'
import { Badge, Button, Empty, Field, Heading, Modal, Notice, Panel, Steps } from '../ui'
import { dateLabel, useData, type Section } from '../state'

function sourceSection(source: Source): Section { return ({ Proyecto: 'Resumen', Objetivo: 'Objetivos y actividades', Actividad: 'Objetivos y actividades', Evidencia: 'Evidencias', Diagnóstico: 'Diagnóstico 360°', Reunión: 'Reuniones' } as Record<string, Section>)[source.kind] ?? 'Resumen' }
export function Reports({ focusId }: { focusId?: string }) {
  const { data, role, run, busy } = useData()
  const [create, setCreate] = useState(false)
  const [selected, setSelected] = useState(focusId ?? '')
  const [confirm, setConfirm] = useState(false)
  const report = data.reports.find(r => r.id === selected)
  return <><Heading eyebrow="El valor de lo que construimos" title="Informes técnicos" description="Transforma el seguimiento del proyecto en un relato respaldado por sus fuentes." action={role !== 'Emprendedor' && <Button onClick={() => setCreate(true)}><Plus size={17} /> Preparar informe</Button>} /><div className="report-banner"><div className="area-icon sand"><FileText size={25} strokeWidth={1.5} /></div><div><h3>El próximo capítulo del acompañamiento</h3><p>Próxima preparación: <b>30 de septiembre de 2026</b> · Periodicidad de ejemplo: 30 días.</p></div><span className="badge neutral">Preparación manual</span></div><Panel title="Historial de informes" action={<span className="small muted">{data.reports.length} versiones</span>}>{data.reports.length ? data.reports.toSorted((a, b) => b.createdAt.localeCompare(a.createdAt)).map(r => <button className="report-row" key={r.id} onClick={() => setSelected(r.id)}><span className="report-icon"><FileText size={25} strokeWidth={1.4} /></span><div><h3>Informe de {r.type === 'FOLLOW_UP' ? 'seguimiento' : 'cierre'}</h3><p>{dateLabel(r.start)} — {dateLabel(r.end)}</p><small>Versión {r.version} · {r.author}{r.approvedBy ? ` · Aprobado por ${r.approvedBy}, ${dateLabel(r.approvedAt!)}` : ''}</small></div><Badge status={r.status} /><ChevronRight size={18} /></button>) : <Empty title="La historia del proyecto empieza aquí" text="Prepara tu primer informe seleccionando un período y sus fuentes." action={role !== 'Emprendedor' && <Button onClick={() => setCreate(true)}>Preparar informe</Button>} />}</Panel><div className="report-principles"><div><Link2 size={20} /><h3>Fuentes a un clic</h3><p>Objetivos, evidencias y diagnósticos respaldan cada sección.</p></div><div><FileCheck2 size={20} /><h3>Revisión humana</h3><p>Los borradores se revisan antes de su aprobación.</p></div><div><History size={20} /><h3>Una historia que se conserva</h3><p>Cada versión aprobada mantiene su propia fotografía.</p></div></div>
    {create && <ReportWizard onClose={() => setCreate(false)} onSaved={id => { setCreate(false); setSelected(id) }} />}
    {report && <Modal title={`Informe de ${report.type === 'FOLLOW_UP' ? 'seguimiento' : 'cierre'} · v${report.version}`} description={`${dateLabel(report.start)} — ${dateLabel(report.end)}`} onClose={() => setSelected('')} wide><div className="report-controls"><Badge status={report.status} />{report.status === 'APPROVED' && <span className="small muted inline"><LockKeyhole size={14} />Versión de solo lectura</span>}</div><ReportDocument report={report} editable={report.status === 'DRAFT' && role !== 'Emprendedor'} />{report.status === 'DRAFT' && role !== 'Emprendedor' && <div className="modal-actions"><Button disabled={busy} onClick={() => run({ type: 'report.status', id: report.id, status: 'SUBMITTED' }, 'Informe enviado a revisión')}>Enviar a revisión <ArrowRight size={16} /></Button></div>}{report.status === 'SUBMITTED' && role !== 'Emprendedor' && <div className="modal-actions"><Button variant="secondary" disabled={busy} onClick={() => run({ type: 'report.status', id: report.id, status: 'DRAFT' }, 'Informe devuelto a borrador')}>Devolver a borrador</Button><Button onClick={() => setConfirm(true)}>Aprobar versión</Button></div>}{report.status === 'APPROVED' && <><Notice>Instantánea aprobada por {report.approvedBy} el {dateLabel(report.approvedAt!)}. La impresión es una copia de demostración; la emisión institucional de PDF corresponde al servicio futuro.</Notice><div className="modal-actions">{role !== 'Emprendedor' && <Button variant="secondary" disabled={busy} onClick={async () => { const next = await run({ type: 'report.revise', id: report.id }, 'Nueva versión creada. La versión aprobada se conserva.'); if (next) setSelected(next.reports.at(-1)!.id) }}>Crear nueva versión</Button>}<Button variant="secondary" onClick={() => window.print()}><Printer size={16} />Imprimir vista aprobada</Button></div></>}</Modal>}
    {confirm && report && <Modal title="Aprobar esta versión del informe" onClose={() => setConfirm(false)}><Notice>Se conservarán la redacción y las fuentes seleccionadas como una instantánea inmutable. Las secciones sin respaldo seguirán indicando Pendiente de completar.</Notice><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirm(false)}>Cancelar</Button><Button disabled={busy} onClick={async () => { if (await run({ type: 'report.status', id: report.id, status: 'APPROVED' }, 'Versión aprobada. Su contenido queda preservado.')) setConfirm(false) }}><Check size={16} />Confirmar aprobación</Button></div></Modal>}
  </>
}
function ReportDocument({ report, editable = false }: { report: Report; editable?: boolean }) {
  const { run, busy, navigate } = useData()
  const [editing, setEditing] = useState<number | null>(null)
  const [content, setContent] = useState('')
  const [sourceIds, setSourceIds] = useState<string[]>([])
  return <article className="report-document"><div className="report-letterhead"><span>CATALITEC <small>TEC Emprende Lab</small></span><span>INFORME TÉCNICO<small>Versión {report.version} · {report.status === 'APPROVED' ? 'Aprobado' : 'Borrador de trabajo'}</small></span></div><h2>{project.name}</h2><p className="muted">{report.type === 'FOLLOW_UP' ? 'Seguimiento del proceso de incubación' : 'Cierre del proceso de incubación'}<br />{dateLabel(report.start)} — {dateLabel(report.end)}</p>{report.sections.map((section, i) => <section className="report-section" key={section.title}><div className="panel-heading"><h3><span>{String(i + 1).padStart(2, '0')}</span>{section.title}</h3>{editable && <button className="text-link no-print" onClick={() => { setEditing(i); setContent(section.content); setSourceIds(section.sourceIds) }}>Editar redacción</button>}</div>{editing === i ? <div className="no-print"><Field label="Redacción del informe"><textarea rows={6} value={content} onChange={e => setContent(e.target.value)} /></Field><p className="small muted">Selecciona fuentes de respaldo para esta redacción. El aporte conserva tu nombre y fecha en el historial.</p>{report.sources.map(src => <label className="check-row" key={src.id}><input type="checkbox" checked={sourceIds.includes(src.id)} onChange={e => setSourceIds(e.target.checked ? [...sourceIds, src.id] : sourceIds.filter(id => id !== src.id))} />{src.title}</label>)}<div className="inline"><Button variant="secondary" onClick={() => setEditing(null)}>Cancelar edición</Button><Button disabled={busy} onClick={async () => { const next = { ...report, sections: report.sections.map((s, index) => index === i ? { ...s, content, sourceIds } : s) }; if (await run({ type: 'report.save', value: next }, 'Redacción guardada con autor y fuentes; registros de origen sin cambios')) setEditing(null) }}>Guardar redacción</Button></div></div> : <p className={section.content === 'Pendiente de completar' ? 'missing-data' : 'report-copy'}>{section.content}</p>}<div className="source-links">{section.sourceIds.map(id => { const source = report.sources.find(s => s.id === id); return source ? <button key={id} title={source.content} onClick={() => navigate(sourceSection(source), source.id)}><Link2 size={12} />{source.title}</button> : null })}</div></section>)}<footer className="report-footer">Preparado por {report.author} · {dateLabel(report.createdAt)}<br />Catalitec / TEC Emprende Lab · Datos ficticios de demostración</footer></article>
}
function ReportWizard({ onClose, onSaved }: { onClose: () => void; onSaved: (id: string) => void }) {
  const { data, role, run, busy } = useData()
  const [step, setStep] = useState(0)
  const [start, setStart] = useState('2026-08-01')
  const [end, setEnd] = useState(TODAY)
  const [type, setType] = useState<Report['type']>('FOLLOW_UP')
  const [selected, setSelected] = useState<string[]>([])
  const [draft, setDraft] = useState<Report | null>(null)
  const [error, setError] = useState('')
  const sources = reportSources(data, start, end)
  return <Modal title="Preparar informe técnico" description="Del seguimiento cotidiano a una fotografía institucional del proyecto." onClose={onClose} wide><Steps labels={['Tipo y período', 'Fuentes', 'Vista previa']} current={step} />{error && <Notice tone="error">{error}</Notice>}{step === 0 ? <><div className="report-type-grid">{(['FOLLOW_UP', 'CLOSURE'] as const).map(t => <button className={`type-card ${type === t ? 'selected' : ''}`} key={t} onClick={() => setType(t)}><FileText size={25} /><strong>{t === 'FOLLOW_UP' ? 'Seguimiento' : 'Cierre'}</strong><p>{t === 'FOLLOW_UP' ? 'Documenta el avance durante un período.' : 'Recoge el proceso al finalizar la incubación.'}</p></button>)}</div><div className="form-grid"><Field label="Inicio del período"><input required type="date" max={end} value={start} onChange={e => setStart(e.target.value)} /></Field><Field label="Fin del período"><input required type="date" min={start} max={TODAY} value={end} onChange={e => setEnd(e.target.value)} /></Field></div><Notice>El borrador utilizará registros del período, objetivos vigentes y la fotografía aprobada anterior como línea base. Las ausencias se marcarán Pendiente de completar.</Notice></> : step === 1 ? <><div className="panel-heading"><h3>Selecciona las fuentes</h3><button className="text-link" onClick={() => setSelected(selected.length === sources.length ? [] : sources.map(s => s.id))}>{selected.length === sources.length ? 'Quitar selección' : 'Seleccionar todas'}</button></div><div className="source-list">{sources.map(s => <label className="check-row" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e => setSelected(e.target.checked ? [...selected, s.id] : selected.filter(id => id !== s.id))} /><div><strong>{s.title}</strong><small>{s.kind} · {dateLabel(s.date)}</small></div></label>)}</div><p className="small muted">{selected.length} fuentes seleccionadas. La narrativa solo sintetiza estos registros.</p></> : draft && <ReportDocument report={draft} />}
    <div className="modal-actions">{step > 0 ? <Button variant="secondary" onClick={() => setStep(step - 1)}><ArrowLeft size={15} />Atrás</Button> : <Button variant="secondary" onClick={onClose}>Cancelar</Button>}{step < 2 ? <Button onClick={() => { if (step === 0) { if (!start || !end || start > end || end > TODAY) { setError('Revisa el período: inicio anterior al fin y fin hasta el 7 de septiembre de 2026.'); return }; setSelected(sources.map(s => s.id)); setStep(1); setError('') } else { try { setDraft(makeReport(data, start, end, type, selected, role)); setStep(2); setError('') } catch (e) { setError((e as Error).message) } } }}>{step === 0 ? 'Revisar fuentes' : 'Generar vista previa'}<ArrowRight size={15} /></Button> : <Button disabled={busy} onClick={async () => { if (draft && await run({ type: 'report.save', value: draft }, 'Borrador de informe generado con fuentes trazables')) onSaved(draft.id) }}>Guardar borrador</Button>}</div>
  </Modal>
}
