import { useState } from 'react'
import { CalendarDays, Check, CheckCircle2, ChevronRight, FileText, LayoutGrid, Link2, List, Paperclip, Plus, Search, Target, Upload } from 'lucide-react'
import type { Activity, Evidence, Objective } from '../data/types'
import { areas, people, project, TODAY } from '../data/seed'
import { actorFor, objectiveProgress, projectProgress, uid } from '../data/repository'
import { Badge, Button, Empty, Field, Heading, Modal, Notice, Panel, Progress, TextLink } from '../ui'
import { dateLabel, initials, useData } from '../state'

export function Work({ focusId }: { focusId?: string }) {
  const { data, role, run, busy, navigate } = useData()
  const [view, setView] = useState<'board' | 'list'>('board')
  const [filter, setFilter] = useState(data.objectives.some(o => o.id === focusId) ? focusId! : 'all')
  const [activityId, setActivityId] = useState(data.activities.some(a => a.id === focusId) ? focusId! : '')
  const [activityForm, setActivityForm] = useState(false)
  const [objectiveForm, setObjectiveForm] = useState<Objective | 'new' | null>(null)
  const [confirm, setConfirm] = useState('')
  const [evidenceForm, setEvidenceForm] = useState(false)
  const activity = data.activities.find(a => a.id === activityId)
  const visible = data.activities.filter(a => filter === 'all' || a.objectiveId === filter)
  const states: Activity['status'][] = ['TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE']
  const card = (a: Activity) => <button className="work-card" key={a.id} onClick={() => setActivityId(a.id)}><span className="eyebrow">{data.objectives.find(o => o.id === a.objectiveId)?.title}</span><h3>{a.title}</h3><div className="inline small muted"><CalendarDays size={13} />{dateLabel(a.date)}</div><footer><span className="avatar">{initials(a.owner)}</span><span className="small muted"><Paperclip size={13} />{data.evidence.filter(e => e.activityId === a.id).length}</span>{a.status === 'DONE' && <CheckCircle2 size={16} className="olive-text" />}</footer></button>
  return <><Heading eyebrow="De la intención a la acción" title="Objetivos y actividades" description="Un plan compartido para avanzar, aprender y dejar evidencia." action={<><Button variant="secondary" onClick={() => setObjectiveForm('new')}><Target size={16} /> Nuevo objetivo</Button><Button onClick={() => setActivityForm(true)}><Plus size={17} /> Nueva actividad</Button></>} /><div className="plan-summary"><div><strong>{Math.round(projectProgress(data))}%</strong><p>avance del proyecto</p></div><Progress value={projectProgress(data)} /><span className="muted small">{data.objectives.filter(o => o.status === 'APPROVED').length} objetivos aprobados · mismo peso</span></div><div className="objectives-strip">{data.objectives.map((o, i) => <div className="objective-strip" key={o.id}><span className="number">0{i + 1}</span><button className="plain objective-name" onClick={() => setFilter(o.id)}><strong>{o.title}</strong><small>{Math.round(objectiveProgress(data, o.id))}% · {data.activities.filter(a => a.objectiveId === o.id).length} actividades</small></button><Badge status={o.status} /><button className="text-link" onClick={() => setObjectiveForm(o)}>Editar</button>{o.status === 'PENDING_APPROVAL' && role !== 'Emprendedor' && <Button variant="secondary" disabled={busy} onClick={() => setConfirm(o.id)}>Aprobar</Button>}</div>)}</div><div className="filters"><div className="segmented"><button className={view === 'board' ? 'selected' : ''} onClick={() => setView('board')}><LayoutGrid size={15} />Kanban</button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}><List size={15} />Lista</button></div><select aria-label="Filtrar actividades por objetivo" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todos los objetivos</option>{data.objectives.map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></div>{view === 'board' ? <div className="kanban">{states.map(state => <section className="kanban-column" key={state}><div className="column-head"><Badge status={state} /><span>{visible.filter(a => a.status === state).length}</span></div>{visible.filter(a => a.status === state).map(card)}{!visible.some(a => a.status === state) && <p className="column-empty">No hay actividades en este estado.</p>}<button className="add-activity" onClick={() => setActivityForm(true)}><Plus size={15} />Agregar actividad</button></section>)}</div> : <Panel>{visible.length ? visible.map(a => <button className="record-row" key={a.id} onClick={() => setActivityId(a.id)}><Target size={18} /><div><strong>{a.title}</strong><p>{data.objectives.find(o => o.id === a.objectiveId)?.title} · {a.owner}</p></div><Badge status={a.status} /><ChevronRight size={16} /></button>) : <Empty text="Agrega actividades a este objetivo para iniciar el trabajo." />}</Panel>}
    {activity && <Modal title={activity.title} description={data.objectives.find(o => o.id === activity.objectiveId)?.title} onClose={() => setActivityId('')}><div className="inline"><Badge status={activity.status} /><span className="muted">{activity.owner}</span></div><div className="definition-grid"><div><span>Fecha prevista</span><strong>{dateLabel(activity.date)}</strong></div><div><span>Finalización</span><strong>{activity.completedAt ? dateLabel(activity.completedAt) : 'Pendiente'}</strong></div></div><h3>Evidencias de la actividad</h3>{data.evidence.filter(e => e.activityId === activity.id).map(e => <button className="record-row" key={e.id} onClick={() => navigate('Evidencias', e.id)}><FileText size={20} /><div><strong>{e.title}</strong><p>{e.author} · {dateLabel(e.date)}</p></div><ChevronRight size={16} /></button>)}{!data.evidence.some(e => e.activityId === activity.id) && <Empty title="El trabajo también cuenta su historia" text="Agrega un archivo, imagen, video o enlace como respaldo de esta actividad." />}<Button variant="secondary" onClick={() => setEvidenceForm(true)}><Paperclip size={16} />Agregar evidencia</Button>{activity.status !== 'DONE' && <><Field label="Estado de trabajo"><select value={activity.status} onChange={e => { if (e.target.value === 'DONE') setConfirm(activity.id); else void run({ type: 'activity.status', id: activity.id, status: e.target.value as Activity['status'] }, 'Estado de actividad actualizado') }}><option value="TODO">Por iniciar</option><option value="IN_PROGRESS">En curso</option><option value="IN_REVIEW">En revisión</option><option value="DONE">Completada</option></select></Field><div className="modal-actions"><Button onClick={() => setConfirm(activity.id)}><Check size={16} />Completar actividad</Button></div></>}{activity.autoComplete && <Notice>Autocompletado habilitado como configuración. Su condición está TBD; el cierre se realiza manualmente en este mockup.</Notice>}</Modal>}
    {activityForm && <ActivityForm defaultObjective={filter === 'all' ? undefined : filter} onClose={() => setActivityForm(false)} />}
    {objectiveForm && <ObjectiveForm initial={objectiveForm === 'new' ? undefined : objectiveForm} onClose={() => setObjectiveForm(null)} />}
    {evidenceForm && <EvidenceForm activityId={activityId} onClose={() => setEvidenceForm(false)} />}
    {confirm && <Modal title={data.objectives.some(o => o.id === confirm) ? 'Aprobar objetivo' : 'Completar actividad'} onClose={() => setConfirm('')}><Notice>{data.objectives.some(o => o.id === confirm) ? 'Este objetivo participará en el avance del proyecto con el mismo peso que los demás objetivos aprobados.' : 'Se registrará la fecha de finalización y se actualizará el avance del proyecto.'}</Notice><div className="modal-actions"><Button variant="secondary" onClick={() => setConfirm('')}>Cancelar</Button><Button disabled={busy} onClick={async () => { const isObjective = data.objectives.some(o => o.id === confirm); if (await run(isObjective ? { type: 'objective.approve', id: confirm } : { type: 'activity.status', id: confirm, status: 'DONE' }, isObjective ? 'Objetivo aprobado' : 'Actividad completada. Avance actualizado.')) setConfirm('') }}>Confirmar</Button></div></Modal>}
  </>
}
function ObjectiveForm({ initial, onClose }: { initial?: Objective; onClose: () => void }) {
  const { data, run, busy } = useData()
  const [draft, setDraft] = useState<Objective>(() => initial ? structuredClone(initial) : { id: uid(), projectId: project.id, areaId: areas[0].id, title: '', description: '', status: 'PENDING_APPROVAL', date: TODAY })
  return <Modal title={initial ? 'Editar objetivo' : 'Crear objetivo operativo'} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); if (await run({ type: 'objective.save', value: draft }, 'Objetivo guardado, pendiente de aprobación')) onClose() }}><Field label="Título"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Área del Cubo 360"><select required value={draft.areaId} onChange={e => setDraft({ ...draft, areaId: e.target.value })}>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</select></Field><Field label="Ambición vinculada (opcional)"><select value={draft.ambitionId ?? ''} onChange={e => setDraft({ ...draft, ambitionId: e.target.value || undefined })}><option value="">Sin ambición vinculada</option>{data.ambitions.map(ambition => <option key={ambition.id} value={ambition.id}>{ambition.title}</option>)}</select></Field><Field label="Descripción y resultado esperado"><textarea required rows={4} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></Field><Notice>{initial?.status === 'APPROVED' ? 'Guardar cambios invalidará la aprobación actual y enviará el objetivo a una nueva aprobación.' : 'El objetivo quedará pendiente de aprobación de un Gestor o Coordinadora.'}</Notice><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Guardar objetivo</Button></div></form></Modal>
}
function ActivityForm({ defaultObjective, onClose }: { defaultObjective?: string; onClose: () => void }) {
  const { data, run, busy } = useData()
  const [draft, setDraft] = useState<Activity>(() => ({ id: uid(), objectiveId: defaultObjective ?? data.objectives[0]?.id ?? '', title: '', owner: 'Andrea Morales', date: '2026-09-18', status: 'TODO', autoComplete: false }))
  return <Modal title="Crear actividad" onClose={onClose}><form onSubmit={async e => { e.preventDefault(); if (await run({ type: 'activity.save', value: draft }, 'Actividad creada y vinculada al objetivo')) onClose() }}><Field label="Nombre de la actividad"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Objetivo asociado"><select required value={draft.objectiveId} onChange={e => setDraft({ ...draft, objectiveId: e.target.value })}>{data.objectives.map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><div className="form-grid"><Field label="Responsable"><select value={draft.owner} onChange={e => setDraft({ ...draft, owner: e.target.value })}>{people.map(p => <option key={p}>{p}</option>)}</select></Field><Field label="Fecha prevista"><input required type="date" value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value })} /></Field></div><label className="check-row"><input type="checkbox" checked={draft.autoComplete} onChange={e => setDraft({ ...draft, autoComplete: e.target.checked })} />Permitir autocompletado</label><p className="small muted">Se conserva la configuración. La condición está TBD y no ejecuta automatización.</p><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Crear actividad</Button></div></form></Modal>
}
export function EvidenceForm({ activityId, onClose }: { activityId?: string; onClose: () => void }) {
  const { data, role, run, busy } = useData()
  const [draft, setDraft] = useState<Evidence>(() => ({ id: uid(), activityId: activityId ?? data.activities[0]?.id ?? '', title: '', type: 'FILE', date: TODAY, author: actorFor(role), content: '', url: '' }))
  return <Modal title="Agregar evidencia" description="Deja un respaldo claro y vinculado al trabajo realizado." onClose={onClose}><form onSubmit={async e => { e.preventDefault(); if (await run({ type: 'evidence.save', value: draft }, 'Evidencia agregada a la actividad')) onClose() }}><Field label="Actividad"><select required value={draft.activityId} onChange={e => setDraft({ ...draft, activityId: e.target.value })}>{data.activities.map(a => <option key={a.id} value={a.id}>{a.title}</option>)}</select></Field><Field label="Tipo de evidencia"><select value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value as Evidence['type'] })}><option value="FILE">Archivo</option><option value="IMAGE">Fotografía</option><option value="VIDEO">Video</option><option value="LINK">Enlace</option></select></Field>{draft.type !== 'LINK' ? <Field label="Seleccionar archivo (simulado)"><input type="file" accept={draft.type === 'IMAGE' ? 'image/*' : draft.type === 'VIDEO' ? 'video/*' : undefined} onChange={e => { const file = e.target.files?.[0]; if (file) setDraft({ ...draft, title: file.name, content: draft.content || `Referencia local: ${file.name} (${Math.round(file.size / 1024)} KB). Archivo seleccionado para esta demostración; no se ha subido a ningún servicio.` }) }} /></Field> : <Field label="URL"><input required type="url" pattern="https?://.*" value={draft.url} onChange={e => setDraft({ ...draft, url: e.target.value })} placeholder="https://…" /></Field>}<Field label="Título"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Descripción del respaldo"><textarea required rows={3} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} /></Field><p className="small muted">Solo se conserva la referencia durante la sesión. No se suben archivos.</p><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Agregar evidencia</Button></div></form></Modal>
}
export function Evidences({ focusId }: { focusId?: string }) {
  const { data, navigate } = useData()
  const [selected, setSelected] = useState(focusId ?? '')
  const [create, setCreate] = useState(false)
  const [query, setQuery] = useState('')
  const evidence = data.evidence.find(e => e.id === selected)
  const visible = data.evidence.filter(e => `${e.title} ${e.author}`.toLowerCase().includes(query.toLowerCase()))
  return <><Heading eyebrow="El respaldo de cada paso" title="Evidencias" description="El trabajo del proyecto, documentado y conectado con sus actividades." action={<Button onClick={() => setCreate(true)}><Upload size={16} />Agregar evidencia</Button>} /><div className="filters"><span className="muted">{data.evidence.length} evidencias en el proyecto</span><label className="search-box"><Search size={16} /><input aria-label="Buscar evidencias" placeholder="Buscar evidencia…" value={query} onChange={e => setQuery(e.target.value)} /></label></div><div className="evidence-grid">{visible.map(e => <button className="evidence-card" key={e.id} onClick={() => setSelected(e.id)}><div className={`evidence-cover ${e.type === 'LINK' ? 'blue' : 'sand'}`}>{e.type === 'LINK' ? <Link2 size={36} strokeWidth={1} /> : <FileText size={38} strokeWidth={1} />}<span>{e.type === 'FILE' ? 'DOCUMENTO' : e.type === 'IMAGE' ? 'FOTOGRAFÍA' : e.type === 'VIDEO' ? 'VIDEO' : 'ENLACE'}</span></div><div><h3>{e.title}</h3><p>{data.activities.find(a => a.id === e.activityId)?.title}</p><footer>{e.author}<small>{dateLabel(e.date)}</small></footer></div></button>)}</div>{!visible.length && <Empty title="Sin evidencias para mostrar" text="Agrega un respaldo o cambia el texto de búsqueda." />}{evidence && <Modal title={evidence.title} onClose={() => setSelected('')}><p className="muted small">Registrada por {evidence.author} · {dateLabel(evidence.date)}</p><div className="document-preview"><FileText size={28} /><h3>Contenido de referencia</h3><p>{evidence.content}</p></div>{evidence.url && <p className="safe-url">Referencia: {evidence.url}</p>}<TextLink onClick={() => navigate('Objetivos y actividades', evidence.activityId)}>Ver actividad de origen</TextLink><Notice>Vista de evidencia de demostración. Los archivos reales se incorporarán con la capa de servicios.</Notice></Modal>}{create && <EvidenceForm onClose={() => setCreate(false)} />}</>
}
