import { cloneElement, isValidElement, useEffect, useId, useRef, type ReactElement, type ReactNode } from 'react'
import { AlertCircle, ArrowDownRight, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Circle, Inbox, LoaderCircle, X } from 'lucide-react'

const statuses: Record<string, [string, string]> = { DRAFT: ['Borrador', 'neutral'], SUBMITTED: ['En revisión', 'blue'], APPROVED: ['Aprobado', 'olive'], ARCHIVED: ['Archivado', 'neutral'], IDENTIFIED: ['Identificada', 'sand'], VALIDATED: ['Validada', 'blue'], IN_PLANNING: ['En planificación', 'blue'], PARTIALLY_ADDRESSED: ['Atendida parcialmente', 'orange'], ADDRESSED: ['Atendida', 'olive'], DISCARDED: ['Descartada', 'neutral'], PENDING_APPROVAL: ['Pendiente de aprobación', 'sand'], TODO: ['Por iniciar', 'neutral'], IN_PROGRESS: ['En curso', 'orange'], IN_REVIEW: ['En revisión', 'blue'], DONE: ['Completada', 'olive'], HIGH: ['Alta', 'orange'], MEDIUM: ['Media', 'sand'], LOW: ['Baja', 'blue'], UNDER_REVIEW: ['En revisión', 'blue'], IN_SIGNATURE_PROCESS: ['En firmas', 'sand'] }
export function Badge({ status }: { status: string }) { const [label, color] = statuses[status] ?? [status, 'neutral']; return <span className={`badge ${color}`}>{['APPROVED', 'DONE', 'ADDRESSED'].includes(status) ? <Check size={12} /> : <Circle size={6} fill="currentColor" />}{label}</span> }
export function Button({ children, onClick, variant = 'primary', disabled = false, type = 'button' }: { children: ReactNode; onClick?: () => void; variant?: 'primary' | 'secondary' | 'ghost'; disabled?: boolean; type?: 'button' | 'submit' }) { return <button type={type} className={`btn ${variant}`} onClick={onClick} disabled={disabled}>{children}</button> }
export function Heading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p className="muted">{description}</p>}</div><div className="heading-actions">{action}</div></div> }
export function Panel({ title, action, children, className = '' }: { title?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{title && <div className="panel-heading"><h2>{title}</h2>{action}</div>}{children}</section> }
export function TextLink({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="text-link" onClick={onClick}>{children}<ArrowUpRight size={15} /></button> }
export function Progress({ value }: { value: number }) { return <div className="progress" role="progressbar" aria-label="Avance" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${value}%` }} /></div> }
export function Delta({ value }: { value?: number }) { return <span className={`delta ${value === undefined || value === 0 ? 'flat' : value > 0 ? 'positive' : 'negative'}`}>{value === undefined ? 'Sin base' : value > 0 ? <><ArrowUpRight size={14} />+{value} avance</> : value < 0 ? <><ArrowDownRight size={14} />{value} retroceso</> : <><ArrowRight size={14} />Sin cambio</>}</span> }
export function Empty({ title = 'Todavía no hay registros', text, action }: { title?: string; text: string; action?: ReactNode }) { return <div className="empty"><div className="empty-icon"><Inbox size={29} strokeWidth={1.3} /></div><h3>{title}</h3><p>{text}</p>{action}</div> }
export function Notice({ children, tone = 'info' }: { children: ReactNode; tone?: 'info' | 'error' | 'success' }) { return <div className={`notice ${tone}`} role={tone === 'error' ? 'alert' : undefined}>{tone === 'success' ? <CheckCircle2 size={18} /> : <AlertCircle size={18} />}<div>{children}</div></div> }
export function Loading() { return <div className="loading" aria-busy="true" role="status"><LoaderCircle className="spin" size={24} /><span>Preparando tu espacio de acompañamiento…</span><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /></div> }
export function Modal({ title, description, onClose, children, wide = false }: { title: string; description?: string; onClose: () => void; children: ReactNode; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null)
  const titleId = useId()
  useEffect(() => { const previous = document.activeElement as HTMLElement; ref.current?.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old; previous?.focus() } }, [])
  return <dialog ref={ref} className={`modal ${wide ? 'wide' : ''}`} onCancel={e => { e.preventDefault(); onClose() }} aria-labelledby={titleId}><header className="modal-head"><div><p className="eyebrow">Lumen Biotech</p><h2 id={titleId}>{title}</h2>{description && <p className="muted">{description}</p>}</div><button className="icon-btn" aria-label="Cerrar panel" onClick={onClose}><X size={20} /></button></header><div className="modal-body">{children}</div></dialog>
}
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { const id = useId(); return <label className="field"><span id={id}>{label}</span>{isValidElement(children) ? cloneElement(children as ReactElement<{ "aria-labelledby"?: string }>, { "aria-labelledby": id }) : children}{hint && <small>{hint}</small>}</label> }
export function Steps({ labels, current }: { labels: string[]; current: number }) { return <div className="steps">{labels.map((label, i) => <span key={label} className={i <= current ? 'current' : ''}><i>{i < current ? <Check size={12} /> : i + 1}</i>{label}{i < labels.length - 1 && <ChevronRight size={14} />}</span>)}</div> }
